"""
env/models.py — Data models for AMR-Steward OpenEnv environment.
Owns: Bhatia
Uses both dataclasses (for internal state) and Pydantic (for API I/O).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Internal state dataclasses (used inside the environment)
# ---------------------------------------------------------------------------

@dataclass
class PatientCase:
    """A single patient episode. Generated by data/patient_generator.py."""
    age: int
    sex: str                           # "M" | "F"
    infection_site: str                # "bacteremia" | "UTI" | "pneumonia" | "intra-abdominal"
    organism: str                      # "K. pneumoniae" | "E. coli" | "P. aeruginosa" | "S. aureus" | "Enterococcus"
    creatinine_clearance: float        # mL/min — kidney function proxy
    allergies: list[str]               # e.g. ["penicillin"]
    antibiogram: dict[str, float]      # drug → MIC value in mg/L
    phenotype: str                     # "susceptible" | "resistant" | "MDR"
    curriculum_level: int              # 1 | 2 | 3


@dataclass
class AMRAction:
    """An action the RL agent can take in the environment."""
    action_type: str                   # "INVESTIGATE" | "COMMIT"
    tool_name: str | None = None       # "interpret_resistance" | "check_guideline" | "assess_patient_factors"
    tool_arg: str | None = None        # drug name or syndrome name, depending on tool
    prescription: dict[str, Any] | None = None  # if COMMIT: {drug, dose, duration, justification}


@dataclass
class AMRObservation:
    """What the agent sees after each step."""
    patient_text: str                  # plain English patient description
    tool_results: list[str] = field(default_factory=list)   # results of tools called so far
    budget_remaining: int = 5
    world_model_rankings: str = ""     # JEPA information-gain predictions (populated by Saaheer's integration)
    done: bool = False

    def to_text(self) -> str:
        """Render the full observation as a single string the LLM sees."""
        parts = [self.patient_text]
        if self.tool_results:
            parts.append("Tool results so far:")
            parts.extend(f"  • {r}" for r in self.tool_results)
        if self.world_model_rankings:
            parts.append(self.world_model_rankings)
        parts.append(f"Budget remaining: {self.budget_remaining} tool call(s).")
        if self.done:
            parts.append("Episode complete.")
        return "\n".join(parts)


# ---------------------------------------------------------------------------
# Pydantic request / response models (used by FastAPI endpoints)
# ---------------------------------------------------------------------------

class StepRequest(BaseModel):
    """Body for POST /step."""
    action_type: str = Field(
        ...,
        description="'INVESTIGATE' to call a diagnostic tool, 'COMMIT' to finalize prescription.",
        examples=["INVESTIGATE", "COMMIT"],
    )
    tool_name: str | None = Field(
        default=None,
        description="Required when action_type='INVESTIGATE'. One of: interpret_resistance, check_guideline, assess_patient_factors.",
    )
    tool_arg: str | None = Field(
        default=None,
        description="Argument for the tool — e.g. drug name or syndrome name.",
    )
    prescription: dict[str, Any] | None = Field(
        default=None,
        description="Required when action_type='COMMIT'. Keys: drug, dose, duration, justification.",
    )

    @field_validator("action_type")
    @classmethod
    def validate_action_type(cls, v: str) -> str:
        allowed = {"INVESTIGATE", "COMMIT"}
        if v not in allowed:
            raise ValueError(f"action_type must be one of {allowed}, got '{v}'")
        return v

    @field_validator("tool_name")
    @classmethod
    def validate_tool_name(cls, v: str | None) -> str | None:
        if v is None:
            return v
        allowed = {"interpret_resistance", "check_guideline", "assess_patient_factors"}
        if v not in allowed:
            raise ValueError(f"tool_name must be one of {allowed}, got '{v}'")
        return v


class ObservationResponse(BaseModel):
    """Serialized AMRObservation returned by /reset and /step."""
    patient_text: str
    tool_results: list[str]
    budget_remaining: int
    world_model_rankings: str
    done: bool
    observation_text: str = Field(description="Full rendered observation string for the LLM.")


class StepResponse(BaseModel):
    """Response body for POST /step."""
    observation: ObservationResponse
    reward: float
    done: bool
    reward_breakdown: dict[str, float] | None = Field(
        default=None,
        description="Per-component reward breakdown. Populated on COMMIT actions.",
    )


class StateResponse(BaseModel):
    """Full serialized episode state from GET /state."""
    patient: dict[str, Any] | None
    tool_results: list[str]
    budget_remaining: int
    done: bool
    curriculum_level: int
    episode_step: int


class HealthResponse(BaseModel):
    status: str
    version: str
